version: '3.8'
services:
  dev-db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    networks:
      - nest-test

networks:
  nest-test: